//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeStructurHead
    {
        public long PK_FeeStructurHeadId { get; set; }
        public Nullable<long> FK_FeeStructurId { get; set; }
        public Nullable<long> FK_FeeHeadId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool IsOptional { get; set; }
    
        public virtual FeeHead FeeHead { get; set; }
        public virtual FeeStructur FeeStructur { get; set; }
    }
}
