//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaperMaster()
        {
            this.PaperQueMasters = new HashSet<PaperQueMaster>();
            this.TestConductMasters = new HashSet<TestConductMaster>();
        }
    
        public long PK_PaperMasterId { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<int> NoOfQuestion { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<int> PassingMarks { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperQueMaster> PaperQueMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestConductMaster> TestConductMasters { get; set; }
    }
}
