//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueOptionMaster
    {
        public long PK_QueOptionMasterId { get; set; }
        public long FK_QueMasterId { get; set; }
        public string Title { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string Details { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual QueMaster QueMaster { get; set; }
    }
}
