//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeeCollectionHead
    {
        public long PK_StudentFeeCollectionHeadId { get; set; }
        public long FK_StudentFeeCollectionId { get; set; }
        public long FK_StudentId { get; set; }
        public long FK_StudentFeeScheduleId { get; set; }
        public decimal PaidAmount { get; set; }
        public Nullable<long> FK_FeeHeadId { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<bool> IsFeeCancel { get; set; }
    
        public virtual FeeHead FeeHead { get; set; }
        public virtual Student Student { get; set; }
        public virtual StudentFeeCollection StudentFeeCollection { get; set; }
        public virtual StudentFeeSchedule StudentFeeSchedule { get; set; }
    }
}
