//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestConductAn
    {
        public long PK_TestConductAnsId { get; set; }
        public long FK_TestConductMasterId { get; set; }
        public long FK_QueMasterId { get; set; }
        public string SelectedAnsOptionId { get; set; }
    
        public virtual QueMaster QueMaster { get; set; }
        public virtual TestConductMaster TestConductMaster { get; set; }
    }
}
