//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestConductMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestConductMaster()
        {
            this.TestConductAns = new HashSet<TestConductAn>();
        }
    
        public long PK_TestConductMasterId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> ConductDateTime { get; set; }
        public Nullable<long> FK_PaperMasterId { get; set; }
        public Nullable<long> ResultMarks { get; set; }
    
        public virtual PaperMaster PaperMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestConductAn> TestConductAns { get; set; }
    }
}
